import { BrokenImagesActions } from '@actions/herokuapp/broken-images-actions';
import { test } from '@fixtures/test';
import { BrokenImagesValidations } from '@validations/herokuapp/broken-images-validations';
import { createBdd } from 'playwright-bdd';
const { Given, When, Then } = createBdd(test);
Given('the example images finished loading', async ({ page }) => { const actions = new BrokenImagesActions(page); await actions.openPage(); await actions.waitForImages(); });
Given('a missing image resource was requested', async ({ page }) => { const actions = new BrokenImagesActions(page); await actions.openPage(); await actions.requestMissingImage(); });
Given('the image classification was available', async ({ page }) => { const actions = new BrokenImagesActions(page); await actions.openPage(); await actions.waitForImages(); });
When('all image requests finish', async ({ page }) => new BrokenImagesActions(page).waitForImages());
When('the user views the valid example image', async ({ page }) => new BrokenImagesActions(page).waitForImages());
When('the user views the broken image entries', async ({ page }) => new BrokenImagesActions(page).waitForImages());
When('the image response is received', async ({ page }) => new BrokenImagesActions(page).waitForImages());
When('the broken image entries are inspected', async ({ page }) => new BrokenImagesActions(page).waitForImages());
When('the user reloads the Broken Images page', async ({ page }) => new BrokenImagesActions(page).reloadPage());
When('the image requests complete in any order', async ({ page }) => new BrokenImagesActions(page).waitForImages());
Then('one example image is loaded successfully', async ({ page }) => new BrokenImagesValidations(page).expectLoadedImageCountToBe(1));
Then('two example images are identified as broken', async ({ page }) => new BrokenImagesValidations(page).expectBrokenImageCountToBe(2));
Then('the image has a positive natural width', async ({ page }) => new BrokenImagesValidations(page).expectValidImageDimensions());
Then('the image has a positive natural height', async ({ page }) => new BrokenImagesValidations(page).expectValidImageDimensions());
Then('each broken image remains represented in the document', async ({ page }) => new BrokenImagesValidations(page).expectEveryImageToRemainInDocument());
Then('the resource status is 404', async ({ page }) => new BrokenImagesValidations(page).expectMissingResourceStatusToBe(404));
Then('none of the broken images has a positive natural width', async ({ page }) => new BrokenImagesValidations(page).expectBrokenImageCountToBe(2));
Then('every example image has a loaded or broken classification', async ({ page }) => new BrokenImagesValidations(page).expectEveryImageToBeClassified());
Then('three example images are classified', async ({ page }) => new BrokenImagesValidations(page).expectEveryImageToBeClassified());
