import { LargeDeepDomActions } from '@actions/herokuapp/large-deep-dom-actions';
import { test } from '@fixtures/test';
import { LargeDeepDomValidations } from '@validations/herokuapp/large-deep-dom-validations';
import { createBdd } from 'playwright-bdd';
const { Given, When, Then } = createBdd(test);
Given('the large data table was visible', async ({ page }) => { const actions = new LargeDeepDomActions(page); await actions.openPage(); await actions.waitForTable(); });
When('the user accesses the deepest no-siblings element', async ({ page }) => new LargeDeepDomActions(page).accessDeepestElement());
When('the user accesses row 50 and column 50', async ({ page }) => new LargeDeepDomActions(page).accessTableCell(50, 50));
When('the table structure is loaded', async ({ page }) => new LargeDeepDomActions(page).waitForTable());
When('the user looks for row 51', async ({ page }) => new LargeDeepDomActions(page).waitForTable());
When('the user looks for column 51', async ({ page }) => new LargeDeepDomActions(page).waitForTable());
When('the user accesses the table boundaries', async ({ page }) => new LargeDeepDomActions(page).accessTableBoundaries());
When('the user accesses the deepest nested content', async ({ page }) => new LargeDeepDomActions(page).accessDeepestElement());
Then('the deepest element displays {string}', async ({ page }, text: string) => new LargeDeepDomValidations(page).expectDeepestTextToBe(text));
Then('the cell value is {string}', async ({ page }, text: string) => new LargeDeepDomValidations(page).expectCellTextToBe(50, 50, text));
Then('fifty rows are present', async ({ page }) => new LargeDeepDomValidations(page).expectTableDimensionsToBe(50, 50));
Then('fifty columns are present', async ({ page }) => new LargeDeepDomValidations(page).expectTableDimensionsToBe(50, 50));
Then('no row 51 is present', async ({ page }) => new LargeDeepDomValidations(page).expectRowNotToExist(51));
Then('no column 51 is present', async ({ page }) => new LargeDeepDomValidations(page).expectColumnNotToExist(51));
Then('the first cell value is {string}', async ({ page }, text: string) => new LargeDeepDomValidations(page).expectCellTextToBe(1, 1, text));
Then('the last cell value is {string}', async ({ page }, text: string) => new LargeDeepDomValidations(page).expectCellTextToBe(50, 50, text));
Then('the nested content is visible', async ({ page }) => new LargeDeepDomValidations(page).expectDeepestTextToBe('No siblings'));
Then('the complete table remains attached', async ({ page }) => new LargeDeepDomValidations(page).expectTableToRemainAttached());
